---
layout: cv
title: Alex Munive's CV
---

# Alex Munive
Economics Student | Data & Research Specialist

<div id="webaddress">
<a href="mailto:alexmunviec@gmail.com">alexmunviec@gmail.com</a>
| <a href="https://linkedin.com/in/alexm-munive">linkedin.com/in/alexm-munive</a>
</div>


## Currently

Student Support Data & Research Specialist at BYU-Idaho

### Specialized in

Data analysis, research design, institutional assessment, and student success strategies

### Research Interests

Higher education analytics, human capital development, economic behavior, and public policy impact

## Education

`Dec 2025`  
__Brigham Young University – Idaho__, Rexburg, ID  
Bachelor of Science in Economics  
- Minor: Data Science  
- GPA: 3.7  
- Relevant Courses: Social Media Marketing, Professional Presentations, Business Writing, Human Resources, Microeconomics, Statistics, Macroeconomics  

`Dec 2023`  
__Brigham Young University – Idaho__, Rexburg, ID  
Human Resources Management Certificate  

## Work Experience

`Jan 2023 – Present`  
__Student Support, BYU-Idaho__, Rexburg, ID  
_Data & Research Specialist_  
- Implemented statistical analyses to develop support programs and data-driven strategies that reduced the percentage of struggling students  
- Created Power BI visual reports to communicate complex statistical information to stakeholders  

`Apr 2023 – Dec 2023`  
__Institutional Research & Assessment, BYU-Idaho__, Rexburg, ID  
_Research & Assessment Specialist_  
- Led focus groups for executive offices, gathering insights into student experiences  
- Presented research findings via reports, presentations, and meetings  
- Conducted evaluations of programs and initiatives based on trends and outcomes  

`Jan 2022 – Jul 2023`  
__Career and Academic Advising, BYU-Idaho__, Rexburg, ID  
_Peer Advisor Team Lead_  
- Organized and led weekly training meetings for 15+ advisors  
- Worked with leadership and department chairs on strategic and curriculum decisions  
- Supported students facing academic challenges by developing recovery pathways  

`Feb 2021 – Aug 2021`  
__Scotiabank__, Mexico City, MX  
_Customer Care Advisor_  
- Assisted 250+ account holders with financial guidance  
- Resolved escalated customer concerns with empathy and professionalism  
- Adhered to privacy and security policies while handling sensitive data  

## Volunteer Experience

`Sep 2017 – Jan 2019`  
__Mexican Red Cross__, Mexico City, Mexico  
_Emergency Medical Technician - B_  
- Responded to emergency calls and administered immediate medical care  
- Managed dispatch operations and resource allocation  
- Delivered life-saving interventions under pressure